version: '3'
services:
    app:
        user: "${UID}:${GID}"
        build: .
        volumes:
            - ./app:/app
        ports:
            - 3000:3000
        depends_on:
            - db
    db:
        image: "mongo:3.6"
        ports:
            - "27017:27017"
        volumes:
            - ./mongo:/data/db
